name: Run CI for PRs against dev branches

on:
  pull_request:
    branches:
      - 'dev-*'


jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      REF: ${{ steps.dcsa-core-branch.outputs.REF }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          server-username: ${{ secrets.DCSA_USER }}
          server-password: ${{ secrets.DCSA_PACKAGES_PAT }}
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v12
        with:
          repositories: '[{ "id": "github", "name": "DCSA Backend repo", "url": "https://maven.pkg.github.com/dcsaorg/DCSA-Core", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } }]'
          servers: '[{ "id": "github", "username": "${{ secrets.DCSA_USER }}", "password": "${{ secrets.DCSA_PACKAGES_PAT }}" }]'

      - name: Checkout dcsaorg/DCSA-Core
        uses: actions/checkout@v2.3.1
        with:
          repository: dcsaorg/DCSA-Core
          ref: ${{env.GITHUB_BASE_REF}}
          path: DCSA-Core
          token: ${{ secrets.REPO_ACCESS_PAT }}

      - name: Set dcsa-core mvn version variable
        run: cd DCSA-Core && echo "DCSA_CORE_PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -Dchangelist='')- " >> $GITHUB_ENV

      - run: echo $DCSA_CORE_PROJECT_VERSION

      - name: Run CI
        run: mvn -B package -Dsha1=-${GITHUB_BASE_REF} -Dchangelist=-SNAPSHOT -Ddcsa.version=$DCSA_CORE_PROJECT_VERSION -Ddcsa.core.tag=${GITHUB_BASE_REF} -Ddcsa.artifacttype=-SNAPSHOT
